#!/usr/bin/env bash
set -x -eu -o pipefail

docker_args=""
if [[ $(uname -m) = arm64 ]]; then
  docker_args="--platform linux/amd64"
fi

# bust cache for apt-get daily
CACHE_APT=$(date '+%Y-%m-%d')

# bust cache for pip when requirements.txt changes
CACHE_PIP=$(shasum -a 256 requirements.txt | cut -f1 -d' ')

# shellcheck disable=SC2086
docker build $docker_args \
    --build-arg CACHE_APT="$CACHE_APT" \
    --build-arg CACHE_PIP="$CACHE_PIP" \
    -t trussworks/circleci \
    .