#!/usr/bin/env bash
set -x -eu -o pipefail

shopt -s extglob
for tag in $CIRCLE_SHA1 ${CIRCLE_BRANCH//+([^A-Za-z0-9-.])/-}; do
    # latest
    docker tag  trussworks/circleci trussworks/circleci:"$tag"
    docker push trussworks/circleci:"$tag"
done

# default tags
if [[ $CIRCLE_BRANCH = main ]]; then
    docker push trussworks/circleci
fi
