#!/bin/bash
set -exu -o pipefail

function test_latest() {
  tag=latest
  echo "Testing ${tag} Dockerfile"

  docker run -it "trussworks/circleci-pre-commit:${tag}" shellcheck --version
  docker run -it "trussworks/circleci-pre-commit:${tag}" pre-commit --version

  echo "Passed ${tag}"
}

tag=latest
echo "* Testing USER is properly set to 'circleci' on '${tag}' tagged image"
docker run -it trussworks/circleci-pre-commit:$tag bash -xc '[[ $(whoami) = circleci ]]'
test_latest

echo Passed.
exit 0