#!/usr/bin/env bash
set -exu -o pipefail

docker_args=""
if [[ $(uname -m) = arm64 ]]; then
  docker_args="--platform linux/amd64"
fi

test_tagged() {
  tag=$1
  echo "Testing $tag Dockerfile"

  docker run $docker_args -it "trussworks/circleci:$tag" shellcheck --version
  docker run $docker_args -it "trussworks/circleci:$tag" pre-commit --version
  docker run $docker_args -it "trussworks/circleci:$tag" terraform --version
  docker run $docker_args -it "trussworks/circleci:$tag" terraform-docs --version
  docker run $docker_args -it "trussworks/circleci:$tag" tfsec --version
  docker run $docker_args -it "trussworks/circleci:$tag" aws --version
  docker run $docker_args -it "trussworks/circleci:$tag" python --version
  docker run $docker_args -it "trussworks/circleci:$tag" go version
  docker run $docker_args -it "trussworks/circleci:$tag" go-bindata --version
  docker run $docker_args -it "trussworks/circleci:$tag" goreleaser --version
  docker run $docker_args -it "trussworks/circleci:$tag" circleci version

  echo "Passed $tag"
}

tag=latest
echo "* Testing USER is properly set to 'circleci' on '$tag' tagged image"
docker run $docker_args -it trussworks/circleci:$tag bash -xc '[[ $(whoami) = circleci ]]'
test_tagged $tag

echo Passed.
exit 0
